In [33]:
# focus on attention head and etc
import torch
import torch.nn as nn
torch.set_printoptions(sci_mode=False)
import torch.functional as F

In [3]:
# all constants 
D_MODEL = 4

In [4]:
# understanding dimensions in pytorch
a = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0],
                  [5.0, 6.0]])
print(torch.sum(a, dim=0, keepdim=True))
print(torch.sum(a, dim=0))
print(torch.sum(a, dim=1, keepdim=True))
print(torch.sum(a, dim=1))
print(torch.sum(a, dim=-1))

tensor([[ 9., 12.]])
tensor([ 9., 12.])
tensor([[ 3.],
        [ 7.],
        [11.]])
tensor([ 3.,  7., 11.])
tensor([ 3.,  7., 11.])


In [5]:
# let's understand softmax
# softmax is a function that takes a vector of K real numbers and normalizes it into a probability distribution consisting of K probabilities proportional to the exponentials of the input numbers.
x = torch.tensor([1.0,2.0,-2.33,-5.66])
def softmax(x):
    return torch.exp(x)/torch.sum(torch.exp(x),dim = 0)

print(x)
print(softmax(x))
torch.sum(softmax(x))

tensor([ 1.0000,  2.0000, -2.3300, -5.6600])
tensor([    0.2663,     0.7238,     0.0095,     0.0003])


tensor(1.)

In [25]:
# learn transpose
a = torch.tensor([[1.0, 2.0],
                  [3.0, 4.0],
                  [5.0, 6.0]])
print(a.shape)
print(a.T)
print(a.T.shape)
print(torch.transpose(a, 0,1))
print(torch.transpose(a, 0,1).shape)

# Suppose we have 3 dimensional space
print("Props of tensor B transpose")
import torch

# Creating a 3D tensor
tensor = torch.tensor([[[1, 2]], 
                       [[5, 6]]])

# Transpose by specifying dimensions
transposed_tensor_01 = tensor.transpose(0, 1)
transposed_tensor_02 = tensor.transpose(0, 2)
transposed_tensor_12 = tensor.transpose(1, 2)

print("Original tensor shape:", tensor.shape)
print("Transposed tensor shape (0, 1):", transposed_tensor_01.shape)
print("Transposed tensor shape (0, 2):", transposed_tensor_02.shape)
print("Transposed tensor shape (1, 2):", transposed_tensor_12.shape)
print("Original tensor:", tensor)
print("Transposed tensor (0, 1):", transposed_tensor_01)
print("Transposed tensor (0, 2):", transposed_tensor_02)
print("Transposed tensor (1, 2):", transposed_tensor_12)


torch.Size([3, 2])
tensor([[1., 3., 5.],
        [2., 4., 6.]])
torch.Size([2, 3])
tensor([[1., 3., 5.],
        [2., 4., 6.]])
torch.Size([2, 3])
Props of tensor B transpose
Original tensor shape: torch.Size([2, 1, 2])
Transposed tensor shape (0, 1): torch.Size([1, 2, 2])
Transposed tensor shape (0, 2): torch.Size([2, 1, 2])
Transposed tensor shape (1, 2): torch.Size([2, 2, 1])
Original tensor: tensor([[[1, 2]],

        [[5, 6]]])
Transposed tensor (0, 1): tensor([[[1, 2],
         [5, 6]]])
Transposed tensor (0, 2): tensor([[[1, 5]],

        [[2, 6]]])
Transposed tensor (1, 2): tensor([[[1],
         [2]],

        [[5],
         [6]]])


In [6]:
wq = torch.randn(D_MODEL, 2)
wk = torch.randn((D_MODEL, 2))
wv = torch.randn((D_MODEL, 2))

In [7]:
print(wq)
print(wk)
print(wv)


tensor([[ 0.4318, -0.8425],
        [ 0.2391, -0.1908],
        [-0.0873,  0.2944],
        [-0.6815, -2.0473]])
tensor([[-0.8148,  1.1438],
        [ 0.6409, -0.3287],
        [ 1.8310, -0.1735],
        [ 1.0375,  0.0264]])
tensor([[-0.3025,  0.5385],
        [ 0.9228,  0.4266],
        [-1.3744,  2.2100],
        [-0.0363, -0.6207]])


In [10]:
xwq = torch.matmul(x, wq)
xwk = torch.matmul(x, wk)
xwv = torch.matmul(x, wv)
print(xwq, xwk, xwv)

tensor([4.9709, 9.6774]) tensor([-9.6715,  0.7413]) tensor([ 4.9507, -0.2445])


In [29]:
attention_score = torch.matmul(xwq , xwk.T )/D_MODEL**0.5
attention_score

tensor(-20.4510)

In [35]:
attention_weights = torch.nn.functional.softmax(attention_score, dim=1)

IndexError: Dimension out of range (expected to be in range of [-1, 0], but got 1)

In [53]:
sentence = "This is a test sentence for An input"
dc = { s:i for i,s in enumerate(sorted(sentence.split(" ")))}
print(dc)

{'An': 0, 'This': 1, 'a': 2, 'for': 3, 'input': 4, 'is': 5, 'sentence': 6, 'test': 7}


In [54]:
import torch 
sentence_int = torch.tensor([dc[s] for s in sentence.split(" ")])
print(sentence_int)

tensor([1, 5, 2, 7, 6, 3, 0, 4])


In [65]:
vocab_size=100 
torch.manual_seed(1337)
d_model = 3 
embed = torch.nn.Embedding(vocab_size, d_model)
embed_sentence = embed(sentence_int).detach()


In [66]:
print(embed)
print(embed_sentence.shape)

Embedding(100, 3)
torch.Size([8, 3])


In [67]:
d_q , d_k, d_v = 2, 2, 4 # d_q and d_k should be of same size 
W_query = torch.nn.Parameter(torch.randn(d_model, d_q)) 
W_key = torch.nn.Parameter(torch.randn(d_model, d_k))
W_value = torch.nn.Parameter(torch.randn(d_model, d_v))


In [70]:
W_query.shape, W_key.shape, W_value.shape, W_query, W_key, W_value


(torch.Size([3, 2]),
 torch.Size([3, 2]),
 torch.Size([3, 4]),
 Parameter containing:
 tensor([[ 1.2038, -2.4643],
         [ 0.0454, -1.0101],
         [ 0.6570, -1.1417]], requires_grad=True),
 Parameter containing:
 tensor([[-0.0126,  0.9385],
         [ 1.7373, -0.4486],
         [-0.3954, -0.7813]], requires_grad=True),
 Parameter containing:
 tensor([[-1.1125,  0.0228, -0.8634, -0.5311],
         [-0.0858, -0.9778, -0.7297,  0.8962],
         [ 0.0630, -0.6822, -0.3909, -0.6245]], requires_grad=True))

In [92]:
x_2 = embed_sentence[1]
x_2

tensor([ 1.5433,  1.3488, -0.1396])

In [93]:
# one token 
x_2

tensor([ 1.5433,  1.3488, -0.1396])

In [94]:
# for one token attention is 
query_2 = torch.matmul(x_2, W_query)
key_2 = torch.matmul(x_2, W_key)
value_2 = torch.matmul(x_2, W_value)


In [95]:
query_2.shape, key_2.shape, value_2.shape, query_2, key_2, value_2

(torch.Size([2]),
 torch.Size([2]),
 torch.Size([4]),
 tensor([ 1.8273, -5.0062], grad_fn=<SqueezeBackward4>),
 tensor([2.3790, 0.9524], grad_fn=<SqueezeBackward4>),
 tensor([-1.8415, -1.1885, -2.2621,  0.4764], grad_fn=<SqueezeBackward4>))

In [99]:
keys = embed_sentence @ W_key
queries = embed_sentence @ W_query

In [100]:

keys.shape , queries.shape, keys, queries

(torch.Size([8, 2]),
 torch.Size([8, 2]),
 tensor([[ 1.0886, -1.1596],
         [ 2.3790,  0.9524],
         [-0.0431,  0.5848],
         [ 2.3434, -0.6660],
         [ 2.4786,  1.4268],
         [-2.1581,  2.1002],
         [ 0.0183,  0.4820],
         [-0.0553,  1.0487]], grad_fn=<MmBackward0>),
 tensor([[-1.0566,  1.5941],
         [ 1.8273, -5.0062],
         [ 1.3893, -2.8295],
         [ 1.0494, -3.3921],
         [-0.9505,  0.6466],
         [ 1.0095, -0.9320],
         [-0.0218,  0.0358],
         [-0.3320,  0.7124]], grad_fn=<MmBackward0>))

In [109]:
print(" one row shape ", queries[1] @ keys[0].T )
print(queries[1] @ keys[0].T,
queries[1] @ keys[1].T ,
queries[1] @ keys[2].T ,
queries[1] @ keys[3].T ,
queries[1] @ keys[4].T ,
queries[1] @ keys[5].T ,
queries[1] @ keys[6].T ,
queries[1] @ keys[7].T )


 one row shape  tensor(7.7941, grad_fn=<DotBackward0>)
tensor(7.7941, grad_fn=<DotBackward0>) tensor(-0.4205, grad_fn=<DotBackward0>) tensor(-3.0061, grad_fn=<DotBackward0>) tensor(7.6164, grad_fn=<DotBackward0>) tensor(-2.6139, grad_fn=<DotBackward0>) tensor(-14.4576, grad_fn=<DotBackward0>) tensor(-2.3796, grad_fn=<DotBackward0>) tensor(-5.3509, grad_fn=<DotBackward0>)


In [108]:
( queries @ keys.T ).shape
# this becomes similar to covariance matrix, noob thing but good
# apply softmax to get attention weights

torch.Size([8, 8])

In [120]:
softmaxy_value =  torch.softmax(( queries @ keys.T )/ d_model ** 0.5, dim=-1 ) 

In [121]:
print(softmaxy_value.shape)
softmaxy_value


torch.Size([8, 8])


tensor([[    0.0053,     0.0168,     0.0525,     0.0039,     0.0245,     0.7699,
             0.0460,     0.0811],
        [    0.5211,     0.0045,     0.0010,     0.4703,     0.0013,     0.0000,
             0.0015,     0.0003],
        [    0.4134,     0.0369,     0.0097,     0.5050,     0.0184,     0.0001,
             0.0120,     0.0045],
        [    0.5242,     0.0183,     0.0087,     0.4265,     0.0077,     0.0001,
             0.0110,     0.0035],
        [    0.0285,     0.0308,     0.1016,     0.0172,     0.0349,     0.5709,
             0.0945,     0.1216],
        [    0.2252,     0.1534,     0.0456,     0.3589,     0.1259,     0.0059,
             0.0499,     0.0352],
        [    0.1200,     0.1233,     0.1262,     0.1193,     0.1244,     0.1337,
             0.1258,     0.1274],
        [    0.0471,     0.0878,     0.1200,     0.0454,     0.1047,     0.3357,
             0.1137,     0.1456]], grad_fn=<SoftmaxBackward0>)

In [123]:
value = embed_sentence @ W_query
attention_score = softmaxy_value @ value
attention_score

tensor([[ 0.8281, -0.8797],
        [-0.0487, -0.7891],
        [ 0.1550, -1.2509],
        [-0.0693, -0.7196],
        [ 0.6862, -0.8743],
        [ 0.3556, -1.6522],
        [ 0.3707, -1.1366],
        [ 0.5136, -0.9952]], grad_fn=<MmBackward0>)